exit status: 0

stdout = """
let and1 : Bool -> Bool -> Bool = fun(x : ?1, y : ?2(x)) => if {x = x, y = y}.x then if {x = x, y = y}.y then true else false else false;
let and2 : Bool -> Bool -> Bool = fun(x : ?5, y : ?6(x)) => if {x = x, y = y}.x then if {x = x, y = y}.y then true else false else false;
let and3 : Bool -> Bool -> Bool = fun(x : ?11, y : ?12(x)) => if {x = x, y = y}.x then if {x = x, y = y}.y then true else false else if {x = x, y = y}.y then false else false;

"""

stderr = """

"""
